profiling:
  enabled: true

  discovery:
    enabled: true
    proc_root: /proc

    exclude:
      pids: []

      users: []

      command_regex:
        - "ipykernel"
        - "jupyter.*kernel"
        - "health[_-]?check"

      executable_regex: []

  pyspy:
    binary: py-spy
    mode: dump
    native: false
